version: '3.7'

services:
  xnat:
    build: /home/mjbarrett/Code/docker-xnat-web
    environment:
      - XNAT_VERSION=1.8.5.1
      - XNAT_ROOT=/data/xnat
      - XNAT_HOME=${XNAT_ROOT}/home
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP:-256m} -Xmx${XNAT_MAX_HEAP:-4g} -Dxnat.home=${XNAT_HOME}
      # BELOW MUST MATCH PSQL ENVIRONMENT
      - POSTGRES_DB=xnat
      - POSTGRES_USER=xnat
      - POSTGRES_PASSWORD=password

    volumes:
      - ./xnat-data/home/logs:${XNAT_HOME}/logs
      - ./xnat-data/archive:${XNAT_ROOT}/archive
      - ./xnat-data/build:${XNAT_ROOT}/build
      - ./xnat-data/cache:${XNAT_ROOT}/cache
      - /var/run/docker.sock:/var/run/docker.sock
  
    depends_on:
      - db

    ports:
      - 8104:8104

    networks:
      - frontend
      - backend

  db:
    image: postgres:12.2-alpine

    ports:
      - "5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=xnat
      - POSTGRES_USER=xnat
      - POSTGRES_PASSWORD=password

    networks:
      - backend

  nginx:
    image: nginx:1.19-alpine-perl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

networks:
  frontend:
  backend:

#static web files in temp filesys
volumes:
  static:
    driver_opts:
      type: tmpfs
      device: tmpfs

