version: '3.7'

services:
  xnat:
    build: /Users/mjbarrett/Code/athena/docker-xnat-web
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP:-256m} -Xmx${XNAT_MAX_HEAP:-4g} -Dxnat.home=${XNAT_HOME:-/data/xnat/home}
      - POSTGRES_DB=${XNAT_DB_NAME:-xnat}
      - POSTGRES_USER=${XNAT_DB_USER:-xnat}
      - POSTGRES_PASSWORD=${XNAT_DB_PASS:-password}

    volumes:
      - ./xnat-data/home/logs:${XNAT_HOME:-/data/xnat/home}/logs
      - ./xnat-data/archive:${XNAT_ROOT:-/data/xnat}/archive
      - ./xnat-data/build:${XNAT_ROOT:-/data/xnat}/build
      - ./xnat-data/cache:${XNAT_ROOT:-/data/xnat}/cache
      - /var/run/docker.sock:/var/run/docker.sock
  
    depends_on:
      - db

    ports:
      - 8104:8104

    networks:
      - frontend
      - backend

  db:
    image: postgres:12.2-alpine

    ports:
      - "5432"

    volumes:
      - ./postgres-data:/data

    environment:
      - POSTGRES_DB=${XNAT_DB_NAME:-xnat}
      - POSTGRES_USER=${XNAT_DB_USER:-xnat}
      - POSTGRES_PASSWORD=${XNAT_DB_PASS:-password}
      - PGDATA=/data

    networks:
      - backend

  nginx:
    build: 
      context: ./nginx/
      args:
        - NGINX_VERSION=1.19-alpine-perl
    depends_on:
      - xnat
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

networks:
  frontend:
  backend:

#static web files in temp filesys
volumes:
  static:
    driver_opts:
      type: tmpfs
      device: tmpfs

