version: '3.7'

services:
  xnat:
    build: ${DXA_XNAT_DOCKERFILE:-https://github.com/barrettMCW/docker-xnat-web.git}
    env_file: ${DXA_CONF_DIR:-./configs/xnat-dev-conf}/xnat/xnat.env

    environment:
      - POSTGRES_HOST=xnatpg
      - POSTGRES_DB=${XNAT_DB_NAME:-xnat}
      - POSTGRES_USER=${XNAT_DB_USER:-xnat}
      - POSTGRES_PASSWORD=${XNAT_DB_PASS:-password}
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP:-256m} -Xmx${XNAT_MAX_HEAP:-4g} -Dxnat.home=/data/xnat/home ${DXA_CATALINA_OPTS}

    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - ${DXA_CONF_DIR:-./xnat-dev-conf}/nginx:/nginx

      - ${DXA_DATA_DIR:-./instance}/cache:/data/xnat/cache
      - ${DXA_DATA_DIR:-./instance}/build:/data/xnat/build
      - ${DXA_LOG_DIR:-./instance}/xnat:/data/xnat/home/logs
      - ${DXA_DATA_DIR:-./instance}/archive:/data/xnat/archive
  
    depends_on:
      - xnatpg

    ports:
      - 8104:8104
      
    networks:
      - frontend
      - backend

  xnatpg:
    image: postgres:12.2-alpine

    ports:
      - "5432"

    volumes:
      - ${DXA_DATA_DIR:-./instance}/postgres-data:/data
      - ${DXA_CONF_DIR:-./configs/xnat-dev-conf}/xnatpg/postgre.conf:/etc/postgresql/postgresql.conf:ro

    environment:
      - POSTGRES_DB=${XNAT_DB_NAME:-xnat}
      - POSTGRES_USER=${XNAT_DB_USER:-xnat}
      - POSTGRES_PASSWORD=${XNAT_DB_PASS:-password}
      - PGDATA=/data

    networks:
      - backend

  nginx:
    build: ${DXA_PROXY_DOCKERFILE:-../../nginxLLAB}

    depends_on:
      xnat:
        condition: service_healthy

    ports:
      - "80:80"
      - "443:443"

    networks:
      - frontend

    volumes:
      - "nginx-conf:/etc/nginx/conf.d/volume"

networks:
  frontend:
  backend:

#static web files in temp filesys
volumes:
  nginx-conf:
    driver_opts:
      type: tmpfs
      device: tmpfs

  xnat-static:
    driver_opts:
      type: tmpfs
      device: tmpfs

