version: '3.7'

services:
  xnat:
    build: 
      context: ${XNAT_DOCKERFILE:-https://github.com/barrettMCW/docker-xnat-web.git}
      args:
        - XNAT_VERSION=${XNAT_VERSION:-1.8.6.1}
    env_file: ${DXA_CONF_DIR:-./configs/xnat-conf}/xnat/xnat.env
    restart: unless-stopped
    
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-xnat}
      - POSTGRES_USER=${POSTGRES_USER:-xnat}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP:-256m} -Xmx${XNAT_MAX_HEAP:-4g} -Dxnat.home=/data/xnat/home ${XNAT_CATALINA_OPTS}
    
    extra_hosts:
    - "host.docker.internal:host-gateway"

    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - ${CERT_DIR:-./certs}/xnat:/etc/ssl/xnat:ro
      - ${DXA_CONF_DIR:-./configs/xnat-conf}/nginx:/nginx
      - ${DXA_CONF_DIR:-./configs/xnat-conf}/xnat/auth/:/data/xnat/home/config/auth/:ro

      - ${DXA_DATA_DIR:-./instance}/cache:/data/xnat/cache
      - ${DXA_DATA_DIR:-./instance}/build:/data/xnat/build
      - ${DXA_DATA_DIR:-./instance}/archive:/data/xnat/archive
      - ${DXA_LOG_DIR:-./instance/logs}/xnat:/data/xnat/home/logs
  
    depends_on:
      - postgres
      
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:${PG_VERSION:-12.2-alpine}
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "pg_isready ", "-d ${POSTGRES_DB:-omero}",
                                  "-U ${POSTGRES_USER:-omero}"]

    volumes:
      - ${PG_DATA_DIR:-./instance}/postgres:/postgres
      - ${DXA_LOG_DIR:-./instance/logs}/postgres/:/log/
      - ${DXA_CONF_DIR:-./configs/xnat-conf}/postgres/pg.conf:/etc/postgresql/postgresql.conf:ro

    environment:
      - PGDATA=/postgres/data/
      - POSTGRES_INITDB_WALDIR=/postgres/wal/
      
      - POSTGRES_DB=${POSTGRES_DB:-xnat}
      - POSTGRES_USER=${POSTGRES_USER:-xnat}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}

    networks:
      - backend

  nginx:
    build: 
      context: ${NGINX_DOCKERFILE:-https://github.com/LavLabInfrastructure/nginxLLAB.git}
      args:
        - NGINX_VERSION=${NGINX_VERSION:-1.19-alpine-perl}
    restart: unless-stopped

    depends_on:
      xnat:
        condition: service_healthy

    ports:
      - "80:80"
      - "443:443"

    networks:
      - frontend

    volumes:
      - "nginx-conf:/etc/nginx/conf.d/volume"

      - ${CERT_DIR:-./certs}/xnat:/etc/ssl/xnat:ro
      - "${DXA_LOG_DIR:-./instance/logs/}/nginx/:/var/log/nginx/"

networks:
  frontend:
  backend:

#static web files in temp filesys
volumes:
  nginx-conf:
    driver_opts:
      type: tmpfs
      device: tmpfs

