version: '3.7'

services:
  xnat:
    build: 
      context: ${XNAT_DOCKERFILE:-https://github.com/LavLabInfrastructure/docker-xnat-web.git}
      args:
        - XNAT_VERSION=${XNAT_VERSION:-1.8.6.1}
    env_file: ${DXA_CONF_DIR:-./configs/xnat-conf}/xnat/xnat.env
    restart: unless-stopped
    
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-root}
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - XNAT_POSTGRES_DB=${XNAT_POSTGRES_DB:-xnat}
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP:-256m} -Xmx${XNAT_MAX_HEAP:-4g} -Dxnat.home=/data/xnat/home ${XNAT_CATALINA_OPTS}

    volumes:
      - ${CERT_DIR:-./certs}/xnat:/etc/ssl/xnat:ro
      - ${DXA_CONF_DIR:-./configs/xnat-conf}/xnat/auth/:/data/xnat/home/config/auth/:ro

      - ${DXA_DATA_DIR:-./instance}/cache:/data/xnat/cache
      - ${DXA_DATA_DIR:-./instance}/build:/data/xnat/build
      - ${DXA_DATA_DIR:-./instance}/archive:/data/xnat/archive
      - ${LOG_DIR:-./instance/logs}/xnat:/data/xnat/home/logs
  
    depends_on:
      postgres:
        condition: service_healthy
      
    networks:
      - frontend
      - xnat-socket
      - backend

  postgres:
    image: postgres:${PG_VERSION:-12.2-alpine}
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-root}", "-U", "${POSTGRES_USER:-root}"]

    volumes:
      - ${PG_DATA_DIR:-./instance}/postgres:/postgres
      - ${LOG_DIR:-./instance/logs}/postgres/:/log/

    environment:
      - PGDATA=/postgres/data/
      - POSTGRES_INITDB_WALDIR=/postgres/wal/
      
      - POSTGRES_DB=${POSTGRES_DB:-root}
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}

    networks:
      - backend

  nginx:
    build: 
      context: ${NGINX_DOCKERFILE:-https://github.com/LavLabInfrastructure/nginxLLAB.git}
      args:
        - NGINX_VERSION=${NGINX_VERSION:-1.19-alpine-perl}
    restart: unless-stopped

    depends_on:
      xnat:
        condition: service_healthy

    ports:
      - "80:80"
      - "443:443"

    networks:
      - frontend

    volumes:
      - ${CERT_DIR:-./certs}/xnat:/etc/ssl/xnat:ro
      - "${LOG_DIR:-./instance/logs/}/nginx/:/var/log/nginx/"
      - ${DXA_CONF_DIR:-./configs/xnat-conf}/nginx:/etc/nginx/conf.d/xnat

  xnatdocker:
    image: tecnativa/docker-socket-proxy
    restart: always
    networks:
      - xnat-socket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - LOG_LEVEL=warning # debug,info,notice,warning,err,crit,alert,emerg
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=1
      - SECRETS=1
      - POST=1 
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=1
      - SERVICES=1
      - SESSION=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VOLUMES=1

networks:
  frontend:
  backend:
  xnat-socket:

#static web files in temp filesys
volumes:
  nginx-conf:
    driver_opts:
      type: tmpfs
      device: tmpfs

